CC = gcc
CFLAGS = -pedantic -std=c99 -Wall -g $(INCLUDES)

CORE_C_FILES = event.c \
          int_list.c \
          mem_wrap.c \
          macros.c \
          system.c 
          
CORE_HEADERS = event.h \
               int_list.h \
               mem_wrap.h \
               macros.h \
               builtin_events.h \
               system.h 

CORE_O_FILES = $(CORE_C_FILES:.c=.o)

CORE_LIB = core.a

.PHONY: all clean
